version: "3.7"
services:
  frontend:
    image: frontend-challenge:dev
    networks:
      default:
        aliases:
        - frontend-challenge.local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    volumes:
      - ./src:/app/src
